### PR TITLE
Feature: Shad Cn UI with functionalities

### PR DESCRIPTION
**Pull request by Om-jannu**

### CODE REVIEW

**Comment by Om-jannu** [comment]
Features :-
- Shadcn Ui
- lazy loading
- User can add multiple resources
- Enhanced Design 

......thank me later 😁

**Comment by Om-jannu** [comment]
preview of the page
image

**Comment by TYPESAFE-RUSTY** [comment]
Hi Om,

Thank you so much for taking the time to submit this pull request and contribute to the project! I really appreciate the effort you've put in, especially the creativity behind the UI changes you've proposed.
For now, I’m planning to stick with the original UI (though I loved your changes!). I understand that using ShadCN is a standard practice compared to vanilla CSS, but I’m more of a vanilla CSS guy and don’t use Tailwind often.
As for lazy loading, I believe it’s not necessary at this point since I’m using Next.js to generate static files and hosting them on GitHub Pages.
By the way, I really loved your design! I’ll definitely consider adding a counter and a "scroll to top" button in future releases.
for now i have cherry picked your data from commit [added my data in datastore](https://github.com/TYPESAFE-RUSTY/contribute-to-this-repo/pull/10/commits/f5d4a6a8d522a7e521533d6c1ff66281f1f09454) and also id like to mention resources you added are really helpful especially so you think you know git 😂.

Best regards,
Typesafe-Rusty

**Comment by TYPESAFE-RUSTY** [comment]
trust me going through 21 changed file was tough, for now your card is visible at the [website](https://typesafe-rusty.github.io/contribute-to-this-repo/) and i am closing this pr.

**Comment by Om-jannu** [comment]
No problem regarding changes in UI everyone has their preferences,
as for the lazy loading part i had tested the original code using a lot of data and it is not related to nextjs loading static file or hosting, whenever a large data source is added or mounted directly on the frontend the frontend cannot handle it, also you are using .map() imagine there are 10,000 contributions.

...just an advice , also good start for others who are new to open source community

**Comment by TYPESAFE-RUSTY** [comment]
got some submissions to do I was actually planning to test your pr and what i have written .

I have a local copy of this pr. thank you once again.
(not expecting 10,000 contributions btw 😭 that will be nightmare to deal with )

**Pull request closed without merging**
